# Generated by Django 6.0.1 on 2026-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_picfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='picfile',
            name='fext',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
